# Generated by Django 5.2.15 on 2026-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
